spring:
  profiles: development
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scheduler?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    initialSize: 5
    maxActive: 50
    minIdle: 1
    maxIdle: 10
    maxWait: 60000
server:
  port: 8000
---
spring:
    profiles: production
server:
    port: 80  
    